### T1 [1 балл]. Сделайте калькулятор произвольных выражений, операции следующие: +, -, /, ^, *. скобок нет

In [1]:
def calculate(input_str):
    blocks = []
    cur=''
    ops = {'^':(lambda x,y: int(x)**int(y)),'/':(lambda x,y: x/y),'*':(lambda x,y: x*y),'+':(lambda x,y: x+y),'-':(lambda x,y: x-y)}
    levels = [['^'], ['*','/'], ['+','-']]
    for c in input_str:
        if(ord('0')<=ord(c)<=ord('9')):
            cur+=c
        elif(c in ops):
            if(len(cur)): blocks.append(cur)
            blocks.append(c)
            cur=''
        else:
            if(len(cur)): blocks.append(cur)
            cur=''
    if(len(cur)): blocks.append(cur)
    
    for level in levels:
        i=1
        while(True):
            if(i>=len(blocks)-1): break
            if(blocks[i] in level):
                op = blocks[i]
                l,r = float(blocks[i-1]), float(blocks[i+1])
                blocks.pop(i+1); blocks.pop(i); blocks.pop(i-1)
                blocks.insert(i-1, ops[op](l,r))
                i-=1
            else:
                i+=1
    
    return float(blocks[0])

#### Дополнить еще 2-мя своими тестами

In [2]:
assert calculate("2 + 2 * 2") == eval("2 + 2 * 2")
assert calculate("345 / 5 * 21") == eval("345 / 5 * 21")
assert calculate("3^3 - 10 + 41 * 3") == eval("3**3 - 10 + 41 * 3")
assert calculate("42 / 7 * 32") == eval("42 / 7 * 32")
assert calculate("100^4 + 7 * 7 * 9 - 16 + 2 - 2 * 2") == eval("100**4 + 7 * 7 * 9 - 16 + 2 - 2 * 2")
assert calculate("18 - 7 * 3 + 63 / 7") == eval("18 - 7 * 3 + 63 / 7")

### T2 [1 балл]. Создайте функцию, которая размножает букву, после которой встретилось число, на это число.
HE2LO -> HELLO (число означает сколько раз встречается буква)

In [3]:
def transform_string(inp_string):
    out=''
    cnt=''
    for c in inp_string:
        if(ord('0')<=ord(c)<=ord('9')):
            cnt+=c
        else:
            if(len(cnt)):
                out+=c*int(cnt)
                cnt=''
            else:
                out+=c
    return out

#### Дополнить еще 2-мя своими тестами

In [4]:
assert transform_string("HE2LO") == "HELLO"
assert transform_string("HI") == "HI"
assert transform_string("пр12ивет") == "приииииииииииивет"
assert transform_string("2л3у78н65тик") == 'ллуууннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннтттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттик'
assert transform_string("0a1b2c3d") == 'bccddd'
assert transform_string("1h2E3l2L1o") == 'hEElllLLo'

### T3 [1 балл]. Создайте функцию, которая выводит статистик по строке: кол-во гласных, согласных, цифр, строчных букв, прописных букв

In [5]:
def string_stat(inp_string):
    vows=0
    cons=0
    digs=0
    lows=0
    upps=0
    for c in inp_string:
        if(c.lower() in 'aeiouyаоуыэеёиюя'): vows+=1
        if(c.lower() in 'bcdfghjklmnpqrstvwxzбвгджзйклмнпрстфхцчшщ'): cons+=1
        if(ord('0')<=ord(c)<=ord('9')): digs+=1
        elif(c==c.lower()): lows+=1
        elif(c==c.upper()): upps+=1
    return (vows, cons, digs, lows, upps)

#### Дополнить еще 2-мя своими тестами

In [6]:
assert string_stat("Тевирп") == (2, 4, 0, 5, 1)
assert string_stat("КоРоВа4") == (3, 3, 1, 3, 3)
assert string_stat("Т41баллНапишите") == (5, 8, 2, 11, 2)
assert string_stat("Напримеризkv1v2вv1k1") == (4, 12, 4, 15, 1)

### Т4 [1 балл]. Напишите функцию, инвертирующую словарь.
Например, из k - [v_1, v_2] в v_1 - [k_1]

In [7]:
def dict_inverter(input_dict):
    dct={}
    for key in input_dict:
        for val in input_dict[key]: 
            if(val not in dct): dct[val]=key
            elif(isinstance(dct[val], list)): dct[val] = dct[val] + [key]
            else: dct[val] = [dct[val], key]
    return dct

#### Дополнить еще 1-м своим тестом

In [8]:
assert dict_inverter({"mango" : ["eatable"], "pillow": ["sleepable"]}) == {"eatable": "mango", "sleepable": "pillow"}
assert dict_inverter({"mango" : ["eatable", "readable"]}) == {"readable":"mango", "eatable":"mango"}
assert dict_inverter({"mango" : ["eatable"], "banana": ["eatable"]}) == {"eatable": ["mango", "banana"]}
assert dict_inverter({"a" : ["1","2"], "b": ["1","2"]}) == {"1" : ["a","b"], "2": ["a","b"]}

### T5 [2 балла]. Средствами NumPy реализуйте функцию для применения метода главных компонент (снижение размерности).
На вход подается двумерная матрица (NxM) и число компонент (k), на выходе получите матрицу сниженной размерности (Nxk)
https://medium.com/analytics-vidhya/understanding-principle-component-analysis-pca-step-by-step-e7a4bb4031d9
#### Протестируйте ее на некоторой матрице

In [9]:
import numpy as np
def PCA(x_:np.ndarray, k:int):
    x = (x_.copy() - x_.mean(axis=0, keepdims=True))/x_.std(axis=0, keepdims=True, ddof=1)
    cov = np.cov(x.T, bias=True)
    eigw, eigv = np.linalg.eig(cov)
    ind = np.argsort(eigw)[::-1][:k]
    eigw, eigv = eigw[ind], eigv.T[ind]
    x = x@eigv.T
    return x
    
X = np.array([[1,2,3,4],[5,5,6,7],[1,4,2,3],[5,3,2,1],[8,1,2,2]]) # из примера по ссылке
PCA(X,2)

array([[ 1.40033078e-02,  7.55974765e-01],
       [-2.55653399e+00, -7.80431775e-01],
       [-5.14801919e-02,  1.25313470e+00],
       [ 1.01415002e+00,  2.38808310e-04],
       [ 1.57986086e+00, -1.22891650e+00]])

### Т6 [4 балла]. Напишите в виде класса NashNumPy свой NumPy, но выполняющий матричные операции только на одномерных и двумерных массивах. Должны быть реализованы следующие операции (в случае, если по правилам линейной алгебры такая операция невозможна, то должна возвращаться соответствующая ошибка):
- создание объекта класса NashNumPy - через список, через заполнение 0, через заполнение 1
- красивое распечатывание объекта класса
- применение некоторой (подаваемой на вход) функции ко всем элементам массива
- размерность объекта класса
- матричное сложение (и разность)
- матричное произведение
- произведение Адамара
- вертикальное соединение
- горизонтальное соединение

#### Напишите собственные проверки работоспособности функции

In [10]:
class NashNumPy:
    def __init__(self, val=None, shape=None):
        self.vals  = None
        self.ndims = None
        self.shape = None
        if(isinstance(val, list)):
            self.vals = val.copy()
            self.ndims = (2 if isinstance(val[0], list) else 1)
            self.shape = ((len(val), len(val[0])) if self.ndims==2 else (len(val),))
        elif(shape is not None):
            self.shape = (shape if isinstance(shape, tuple) else (shape, ))
            self.ndims = len(shape)
            if(self.ndims==1):
                self.vals = [val for i in range(shape[0])]
            else:
                self.vals = [[val for j in range(shape[1])] for i in range(shape[0])]
        else:
            raise ValueError
    
    @staticmethod
    def zeros(shape):
        return NashNumPy(0., shape)
    
    @staticmethod
    def ones(shape):
        return NashNumPy(1., shape)
    
    @staticmethod
    def hstack(arrs):
        if(len(arrs)<2):
            raise ValueError
        for i in range(len(arrs)-1):
            if(arrs[i].ndims != arrs[i+1].ndims and (arrs[i].ndims==1 or arrs[i].shape[0] == arrs[i+1].shape[0])):
                raise ValueError
        vals = ([[] for i in range(arrs[0].shape[0])] if arrs[0].ndims==2 else [])
        for arr in arrs:
            if(arr.ndims==1): 
                for v in arr.vals: vals.append(v)
            else:
                for i in range(arr.shape[0]):
                    vals[i].extend(arr.vals[i])
        return NashNumPy(vals)
    
    @staticmethod
    def vstack(arrs):
        if(len(arrs)<2):
            raise ValueError
        for i in range(len(arrs)-1):
            if(arrs[i].ndims != arrs[i+1].ndims and (arrs[i].ndims==1 or arrs[i].shape[1] == arrs[i+1].shape[1])):
                raise ValueError
        vals = []
        for arr in arrs:
            if(arr.ndims==1): 
                for v in arr.vals: vals.append(v)
            else:
                for row in arr.vals:
                    vals.append(row.copy())
        return NashNumPy(vals)
    
    def __str__(self):
        tp = ('vector' if self.ndims==1 else 'matrix')+'('
        s = tp+"["
        for i,row in enumerate(self.vals):
            s+=(" "*(len(tp)+1) if i>0 else "") + str(row)+(f"], shape={self.shape})" if i==(self.shape[0]-1) else "\n")
        return s
    
    def __repr__(self):
        return self.__str__()
    
    def apply_wise(self, func):
        v = self.vals.copy()
        if(self.ndims==1):
            for i in range(self.shape[0]): v[i] = func(v[i])
        else:
            for i in range(self.shape[0]):
                for j in range(self.shape[1]):
                    v[i][j] = func(v[i][j])
        return NashNumPy(v)
    
    def sum(self, other):
        if(self.shape != other.shape):
            raise ValueError
        res = NashNumPy.zeros(self.shape)
        if(self.ndims==1):
            for i in range(self.shape[0]):
                res.vals[i] = self.vals[i] + other.vals[i]
        else:
            for i in range(self.shape[0]):
                for j in range(self.shape[1]):
                    res.vals[i][j] = self.vals[i][j] + other.vals[i][j]
        return res
    
    def sub(self, other):
        if(self.shape != other.shape):
            raise ValueError
        res = NashNumPy.zeros(self.shape)
        if(self.ndims==1):
            for i in range(self.shape[0]):
                res.vals[i] = self.vals[i] - other.vals[i]
        else:
            for i in range(self.shape[0]):
                for j in range(self.shape[1]):
                    res.vals[i][j] = self.vals[i][j] - other.vals[i][j]
        return res
    
    def mul(self, other): # Adamar's multiplication
        if(self.shape != other.shape):
            raise ValueError
        res = NashNumPy.zeros(self.shape)
        if(self.ndims==1):
            for i in range(self.shape[0]):
                res.vals[i] = self.vals[i] * other.vals[i]
        else:
            for i in range(self.shape[0]):
                for j in range(self.shape[1]):
                    res.vals[i][j] = self.vals[i][j] * other.vals[i][j]
        return res
    
    def matmul(self, other):
        if(self.ndims==1 or self.shape[1]!=other.shape[0]):
            raise ValueError
        res = NashNumPy.zeros((self.shape[0], other.shape[1]))
        for i in range(res.shape[0]):
            for j in range(res.shape[1]):
                for k in range(self.shape[1]):
                    res.vals[i][j] += self.vals[i][k] * other.vals[k][j]
        return res

In [11]:
a=NashNumPy([[1,2,3], [4,5,6]])
b=NashNumPy.ones((3,3))
c = a.matmul(b)
c

matrix([[6.0, 6.0, 6.0]
        [15.0, 15.0, 15.0]], shape=(2, 3))

In [12]:
NashNumPy.vstack((a,b,c))

matrix([[1, 2, 3]
        [4, 5, 6]
        [1.0, 1.0, 1.0]
        [1.0, 1.0, 1.0]
        [1.0, 1.0, 1.0]
        [6.0, 6.0, 6.0]
        [15.0, 15.0, 15.0]], shape=(7, 3))

In [13]:
NashNumPy.hstack((a,c)).apply_wise(lambda x: x**2)

matrix([[1, 4, 9, 36.0, 36.0, 36.0]
        [16, 25, 36, 225.0, 225.0, 225.0]], shape=(2, 6))

In [14]:
a.sum(c)

matrix([[7.0, 8.0, 9.0]
        [19.0, 20.0, 21.0]], shape=(2, 3))

In [15]:
a.sub(c)

matrix([[-5.0, -4.0, -3.0]
        [-11.0, -10.0, -9.0]], shape=(2, 3))

In [16]:
a.mul(c)

matrix([[6.0, 12.0, 18.0]
        [60.0, 75.0, 90.0]], shape=(2, 3))

In [17]:
a=NashNumPy([1,2,3])
b=NashNumPy.ones((3,))
a.sub(b)

vector([0.0
        1.0
        2.0], shape=(3,))

In [18]:
a.sum(b)

vector([2.0
        3.0
        4.0], shape=(3,))

In [19]:
a.mul(b)

vector([1.0
        2.0
        3.0], shape=(3,))

In [20]:
a.apply_wise(lambda x: x**2)

vector([1
        4
        9], shape=(3,))